apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prozorro-pdf.fullname" . }}-nginx-conf
  labels:
    {{- include "prozorro-pdf.labels" . | nindent 4 }}
data:
  nginx.conf: |-

    server {
        listen 8000;
        server_name _;

        client_max_body_size 5M;
        access_log off;
        server_tokens off;

        include /etc/nginx/mime.types;

        root /usr/share/nginx/html;
        index index.html;
        set_real_ip_from 10.0.0.0/8;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;


        location / {
            try_files $uri $uri/ =404;
        }

        location ~* \.(ttf|otf|woff|woff2)$ {
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Cache-Control "private, max-age=31536000" always;
            expires 1y;
        }

        gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
        gzip on;
    }

