export enum PROZORRO_PDF_TYPES {
  PQ = "pq",
  EDR = "edr",
  EDR_2 = "edr_2",
  NAZK = "nazk",
  TICKET = "ticket",
  COMPLAINT = "complaint",
  CONCLUSION = "conclusion",
  ANNOUNCEMENT = "announcement",
  DETERMINING_WINNER_OF_PROCUREMENT = "determining_winner_of_procurement",
  TENDER_REJECTION_PROTOCOL = "tender_rejection_protocol",
  PURCHASE_CANCELLATION_PROTOCOL = "purchase_cancellation_protocol",
  ANNUAL_PROCUREMENT_PLAN = "annual_procurement_plan",
  PROTOCOL_CONSIDERATION_TENDER_OFFERS = "protocol_consideration_tender_offers",
  PROTOCOL_ON_EXTENSION_OF_REVIEW_PERIOD = "protocol_on_extension_of_review_period",
  TENDER_OFFER = "tender_offer",
  COMPLAINT_POST = "complaint_post",
  DEVIATION_REPORT = "deviation_report",
}
