import * as PDF_HELPER_CONST from "@/constants/pdf/pdfHelperConstants";

export const NAZK_PAGE_MARGIN = [
  PDF_HELPER_CONST.MARGIN_40,
  PDF_HELPER_CONST.MARGIN_40,
  PDF_HELPER_CONST.MARGIN_40,
  PDF_HELPER_CONST.MARGIN_120,
];
