import * as PDF_HELPER_CONST from "@/constants/pdf/pdfHelperConstants";

export const PQ_GENERIC_TABLE_ITEMS_WIDTH = [
  PDF_HELPER_CONST.ROW_WIDTH_20,
  PDF_HELPER_CONST.ROW_WIDTH_150,
  PDF_HELPER_CONST.ROW_WIDTH_65,
  PDF_HELPER_CONST.ROW_WIDTH_65,
  PDF_HELPER_CONST.ROW_WIDTH_90,
  PDF_HELPER_CONST.ROW_ALL_WIDTH,
];

export const PQ_GENERIC_TABLE_ADDRESS_WIDTH = [PDF_HELPER_CONST.ROW_WIDTH_150, PDF_HELPER_CONST.ROW_WIDTH_340];

export const PQ_GENERIC_TABLE_ATTRIBUTES_WIDTH = [PDF_HELPER_CONST.ROW_WIDTH_245, PDF_HELPER_CONST.ROW_WIDTH_245];

export const PQ_TABLE_ITEMS_WIDTH = [
  PDF_HELPER_CONST.ROW_WIDTH_20,
  PDF_HELPER_CONST.ROW_WIDTH_100,
  PDF_HELPER_CONST.ROW_WIDTH_100,
  PDF_HELPER_CONST.ROW_WIDTH_70,
  PDF_HELPER_CONST.ROW_WIDTH_70,
  PDF_HELPER_CONST.ROW_WIDTH_70,
  PDF_HELPER_CONST.ROW_ALL_WIDTH,
];

export const PQ_AOZ_ITEM_TERMS_TABLE_WIDTH = [
  PDF_HELPER_CONST.ROW_WIDTH_20,
  PDF_HELPER_CONST.ROW_WIDTH_300,
  PDF_HELPER_CONST.ROW_ALL_WIDTH,
];

export const PQ_AOZ_ITEM_QUANTITY_TABLE_WIDTH = [
  PDF_HELPER_CONST.ROW_WIDTH_20,
  PDF_HELPER_CONST.ROW_WIDTH_340,
  PDF_HELPER_CONST.ROW_ALL_WIDTH,
];

export const PQ_AOZ_ACT_OF_ACCEPTANCE_AND_TRANSFER_TABLE_WIDTH = [
  PDF_HELPER_CONST.ROW_WIDTH_20,
  PDF_HELPER_CONST.ROW_WIDTH_200,
  PDF_HELPER_CONST.ROW_WIDTH_110,
  PDF_HELPER_CONST.ROW_WIDTH_50,
  PDF_HELPER_CONST.ROW_WIDTH_90,
  PDF_HELPER_CONST.ROW_WIDTH_70,
  PDF_HELPER_CONST.ROW_WIDTH_70,
  PDF_HELPER_CONST.ROW_ALL_WIDTH,
];

export const PQ_AOZ_EXPENSE_INVOICE_FORM_TABLE_WIDTH = [PDF_HELPER_CONST.ROW_WIDTH_125, PDF_HELPER_CONST.ROW_ALL_WIDTH];
