import { PROZORRO_TEMPLATE_CODES } from "@/widgets/pq/types/TemplateCodes.enum";
import { TemplateVersionsEnum } from "@/widgets/pq/types/TemplateVersions.enum";

export const TemplateVersionsMap = new Map<TemplateVersionsEnum, PROZORRO_TEMPLATE_CODES[]>()
  .set(TemplateVersionsEnum.VERSION_1, [
    PROZORRO_TEMPLATE_CODES.OTHER,
    PROZORRO_TEMPLATE_CODES.GAS,
    PROZORRO_TEMPLATE_CODES.PHARM,
    PROZORRO_TEMPLATE_CODES.MEDICINE,
    PROZORRO_TEMPLATE_CODES.COMPUTER,
    PROZORRO_TEMPLATE_CODES.FRUIT,
  ])
  .set(TemplateVersionsEnum.VERSION_2, [
    PROZORRO_TEMPLATE_CODES.GENERIC,
    PROZORRO_TEMPLATE_CODES.FOOD,
    PROZORRO_TEMPLATE_CODES.FRUIT2,
    PROZORRO_TEMPLATE_CODES.GAS2,
    PROZORRO_TEMPLATE_CODES.PHARM2,
    PROZORRO_TEMPLATE_CODES.MEDICINE2,
    PROZORRO_TEMPLATE_CODES.SOFTWARE,
    PROZORRO_TEMPLATE_CODES.NUSH,
  ]);
